# Generated by Django 5.1.3 on 2024-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
