# Generated by Django 5.1.3 on 2024-11-25 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sporpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkonomiPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='ekonomi_images/')),
                ('categories', models.ManyToManyField(blank=True, related_name='ekonomi_posts', to='core.category')),
            ],
        ),
    ]
